# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-Vagrant-9-latest.x86_64.vagrant-libvirt.box"

  config.vm.provider :libvirt do |domain|
      domain.memory = "16384"
      domain.cpus = 8
  end
  config.vm.hostname = "speasy-proxy"
  config.vm.provision "file", source: "./sciqlop-proxy.conf", destination: "~/sciqlop-proxy.conf" 
  config.vm.synced_folder "../", "/home/vagrant/speasy_proxy/", type: "rsync", rsync__exclude: "../../.git/"


  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", inline: <<-SHELL
     sudo dnf update -y
     mkdir -p /DATA/speasy_proxy /DATA/log/speasy
     mkdir -p /DATA/speasy_proxy_dev /DATA/log_dev/speasy
     mkdir -p /archive_cache/nginx/data /archive_cache/nginx/proxy_temp
     chown -R nginx:nginx /archive_cache/nginx
     sudo chmod -R 777 /DATA
     sudo dnf install -y nginx podman podman-docker.noarch
     sudo mv /home/vagrant/sciqlop-proxy.conf /etc/nginx/conf.d/sciqlop-proxy.conf
     sed -i  s/SELINUX=enforcing/SELINUX=disabled/ /etc/selinux/config
     sudo setenforce 0
     systemctl enable --now nginx
     cd /home/vagrant/speasy_proxy/docker/ && sudo sh ./build.sh && sudo sh ./build.sh 6544 speasy_proxy_dev git+https://github.com/SciQLop/speasy
     export IP=`hostname -I | cut -d' ' -f1`
     sudo podman run --restart unless-stopped --ulimit nofile=262144:262144 -d -v /DATA/speasy_proxy:/data -v /DATA/log:/log -e SPEASY_CACHE_SIZE="1e10" -e SPEASY_PROXY_PREFIX='/cache' -e SPEASY_PROXY_URL="http://$IP" -p6543:6543 --name speasy-proxy speasy_proxy
     sudo podman run --restart unless-stopped --ulimit nofile=262144:262144 -d -v /DATA/speasy_proxy_dev:/data -v /DATA/log_dev:/log -e SPEASY_PROXY_LOG_LEVEL="INFO" -e SPEASY_CACHE_SIZE="1e10" -e SPEASY_PROXY_PREFIX='/cache-dev' -e PORT=6544 -e SPEASY_PROXY_URL="http://$IP" -p6544:6544 --name speasy-proxy-dev speasy_proxy_dev
   SHELL
end
