# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/33-cloud-base"

  config.vm.provider :libvirt do |domain|
      domain.memory = "16384"
      domain.cpus = 8
  end
  config.vm.hostname = "spwc-proxy"
  config.vm.provision "file", source: "./sciqlop-proxy.conf", destination: "~/sciqlop-proxy.conf" 
  config.vm.synced_folder "../../spwc_proxy", "/home/vagrant/spwc_proxy", type: "rsync", rsync__exclude: "../../.git/"


  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", inline: <<-SHELL
     sudo dnf update -y
     mkdir -p /DATA/spwc_proxy /DATA/log/spwc
     mkdir -p /DATA/spwc_proxy_dev /DATA/log_dev/spwc
     sudo chmod -R 777 /DATA
     sudo dnf install -y nginx podman podman-docker.noarch
     sudo mv /home/vagrant/sciqlop-proxy.conf /etc/nginx/conf.d/sciqlop-proxy.conf
     sed -i  s/SELINUX=enforcing/SELINUX=disabled/ /etc/selinux/config
     sudo setenforce 0
     systemctl enable --now nginx
     cd /home/vagrant/spwc_proxy/docker/ && sudo sh ./build.sh && sudo sh ./build.sh 6544 spwc_proxy_dev
     export IP=`hostname -I | cut -d' ' -f1`
     sudo podman run --restart unless-stopped --ulimit nofile=262144:262144 -d -v /DATA/spwc_proxy:/data -v /DATA/log:/log -e SPWC_CACHE_SIZE="1e10" -e SPWC_PROXY_PREFIX='/cache' -e SPWC_PROXY_URL="http://$IP" -p6543:6543 --name spwc-proxy spwc_proxy
     sudo podman run --restart unless-stopped --ulimit nofile=262144:262144 -d -v /DATA/spwc_proxy_dev:/data -v /DATA/log_dev:/log -e SPWC_CACHE_SIZE="1e10" -e SPWC_PROXY_PREFIX='/cache-dev' -e PORT=6544 -e SPWC_PROXY_URL="http://$IP" -p6544:6544 --name spwc-proxy-dev spwc_proxy_dev
   SHELL
end
