openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Speasy proxy
paths:
  /:
    get:
      responses:
        200:
          description: home page
  /get_speasy_version:
    get:
      responses:
        200:
          description: proxy SPEASY version
  /get_version:
    get:
      responses:
        200:
          description: proxy version
  /get_data:
    get:
      parameters:
        - name: path
          in: query
          required: true
          schema:
            type: string
            minLength: 3
          example: amda/c1_b_gsm
        - name: format
          in: query
          required: false
          schema:
            type: string
            enum: [ python_dict, speasy_variable ]
          example: python_dict
        - name: zstd_compression
          in: query
          required: false
          schema:
            type: boolean
          example: true
        - name: coordinate_system
          in: query
          required: false
          schema:
            type: string
            enum: [geo, gm, gse, gsm, sm, geitod, geij2000]
          example: gse
        - $ref: "#/components/parameters/StartDateParam"
        - $ref: "#/components/parameters/StopDateParam"
        - $ref: '#/components/parameters/PickleProtocolParam'
      responses:
        200:
          description: Returns pickled data
        400:
          description: Bad Request
  /get_cache_entries:
    get:
      parameters:
        - $ref: '#/components/parameters/PickleProtocolParam'
      responses:
        200:
          description: Returns pickled data\ No newline at end of file

components:
  schemas:
    Date:
      type: string
      pattern: ([0-9]{4})-([0-9]{2})-([0-9]{2})(T| )([0-9]{2}):([0-9]{2}):([0-9]{2})Z?
  parameters:
    PickleProtocolParam:
      name: pickle_proto
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 3
        default: 3
        maximum: 5
    StartDateParam:
      name: start_time
      in: query
      required: true
      schema:
        $ref: "#/components/schemas/Date"
      example: "2018-10-24T00:00:00"
    StopDateParam:
      name: stop_time
      in: query
      required: true
      schema:
        $ref: "#/components/schemas/Date"
      example: "2018-10-24T00:01:00"

